%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /home/henrik/Documents/myslab/test.xlsx
%    Worksheet: sheet1
%
% Auto-generated by MATLAB on 12-Oct-2022 18:05:17

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 1);

% Specify sheet and range
opts.Sheet = "sheet1";
opts.DataRange = "A2:A487";

% Specify column names and types
opts.VariableNames = "VoltageFormulaResult";
opts.VariableTypes = "double";

% Import the data
test = readtable("/home/henrik/Documents/myslab/test.xlsx", opts, "UseExcel", false);

%% Convert to output type
test = table2array(test);

%% Clear temporary variables
clear opts